"""empty message

Revision ID: 26e476b49d36
Revises: 6eb1aacc7ee8
Create Date: 2025-11-14 21:20:41.130984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e476b49d36'
down_revision: Union[str, Sequence[str], None] = '6eb1aacc7ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estacionamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_vaga', sa.String(), nullable=False),
    sa.Column('tipo_vaga', sa.Enum('MOTO', 'CARRO', 'PCD', 'CARRO_ELETRICO', name='tipo_vaga'), nullable=False),
    sa.Column('posicao_geral', sa.Integer(), nullable=False),
    sa.Column('posicao_x', sa.Float(), nullable=False),
    sa.Column('posicao_y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('MOTO', 'CARRO', 'PCD', 'CARRO_ELETRICO', name='tipo_automovel'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacionamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipo_movimento'), nullable=False),
    sa.Column('horario', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estacionamento_id'], ['estacionamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('local_trabalho', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'local_trabalho')
    op.drop_table('registro_atividade')
    op.drop_table('automoveis')
    op.drop_table('estacionamentos')
    # ### end Alembic commands ###
