"""empty message

Revision ID: 692ce065558e
Revises: fa8288192e47
Create Date: 2025-11-15 06:52:28.058286

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "692ce065558e"
down_revision: Union[str, Sequence[str], None] = "fa8288192e47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locais_trabalho",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("posicao_x", sa.Float(), nullable=False),
        sa.Column("posicao_y", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
    )

    # Use batch_alter_table para compatibilidade com SQLite
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_usuarios_local_trabalho",  # Nome explícito para a constraint
            "locais_trabalho",
            ["local_trabalho"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Use batch_alter_table para compatibilidade com SQLite
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_usuarios_local_trabalho",  # Mesmo nome usado no upgrade
            type_="foreignkey",
        )

    op.drop_table("locais_trabalho")
    # ### end Alembic commands ###
