"""empty message

Revision ID: fa8288192e47
Revises: eaa88a1a9adc
Create Date: 2025-11-15 06:23:58.989975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8288192e47'
down_revision: Union[str, Sequence[str], None] = 'eaa88a1a9adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caminhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_x', sa.Integer(), nullable=False),
    sa.Column('origem_y', sa.Integer(), nullable=False),
    sa.Column('destino_x', sa.Integer(), nullable=False),
    sa.Column('destino_y', sa.Integer(), nullable=False),
    sa.Column('direcao', sa.Enum('IDA', 'VOLTA', 'AMBOS', name='direcao_caminho'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caminhos')
    # ### end Alembic commands ###
